name: curl_http
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/ky1vstar/curl.dart/tree/master/curl_http
issue_tracker: https://github.com/ky1vstar/curl.dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  libcurl:
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  lint: ^2.0.1
  test: ^1.16.0

dependency_overrides:
  libcurl:
    path: ../libcurl
