// ignore_for_file: constant_identifier_names

import 'package:curl_http/src/curl/bindings.g.dart';

// `static const int CURLINFO_(\w+).*;`
// ->
// `/// API docs: https://curl.se/libcurl/c/CURLINFO_$1.html\n  $1(CURLINFO.CURLINFO_$1),\n`

/// API docs: https://curl.se/libcurl/c/curl_easy_getinfo.html
enum CurlEasyInfo {
  NONE(CURLINFO.CURLINFO_NONE),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_EFFECTIVE_URL.html
  EFFECTIVE_URL(CURLINFO.CURLINFO_EFFECTIVE_URL),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_RESPONSE_CODE.html
  RESPONSE_CODE(CURLINFO.CURLINFO_RESPONSE_CODE),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_TOTAL_TIME.html
  TOTAL_TIME(CURLINFO.CURLINFO_TOTAL_TIME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_NAMELOOKUP_TIME.html
  NAMELOOKUP_TIME(CURLINFO.CURLINFO_NAMELOOKUP_TIME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CONNECT_TIME.html
  CONNECT_TIME(CURLINFO.CURLINFO_CONNECT_TIME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PRETRANSFER_TIME.html
  PRETRANSFER_TIME(CURLINFO.CURLINFO_PRETRANSFER_TIME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SIZE_UPLOAD.html
  SIZE_UPLOAD(CURLINFO.CURLINFO_SIZE_UPLOAD),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SIZE_UPLOAD_T.html
  SIZE_UPLOAD_T(CURLINFO.CURLINFO_SIZE_UPLOAD_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SIZE_DOWNLOAD.html
  SIZE_DOWNLOAD(CURLINFO.CURLINFO_SIZE_DOWNLOAD),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SIZE_DOWNLOAD_T.html
  SIZE_DOWNLOAD_T(CURLINFO.CURLINFO_SIZE_DOWNLOAD_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SPEED_DOWNLOAD.html
  SPEED_DOWNLOAD(CURLINFO.CURLINFO_SPEED_DOWNLOAD),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SPEED_DOWNLOAD_T.html
  SPEED_DOWNLOAD_T(CURLINFO.CURLINFO_SPEED_DOWNLOAD_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SPEED_UPLOAD.html
  SPEED_UPLOAD(CURLINFO.CURLINFO_SPEED_UPLOAD),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SPEED_UPLOAD_T.html
  SPEED_UPLOAD_T(CURLINFO.CURLINFO_SPEED_UPLOAD_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_HEADER_SIZE.html
  HEADER_SIZE(CURLINFO.CURLINFO_HEADER_SIZE),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_REQUEST_SIZE.html
  REQUEST_SIZE(CURLINFO.CURLINFO_REQUEST_SIZE),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SSL_VERIFYRESULT.html
  SSL_VERIFYRESULT(CURLINFO.CURLINFO_SSL_VERIFYRESULT),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_FILETIME.html
  FILETIME(CURLINFO.CURLINFO_FILETIME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_FILETIME_T.html
  FILETIME_T(CURLINFO.CURLINFO_FILETIME_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CONTENT_LENGTH_DOWNLOAD.html
  CONTENT_LENGTH_DOWNLOAD(CURLINFO.CURLINFO_CONTENT_LENGTH_DOWNLOAD),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CONTENT_LENGTH_DOWNLOAD_T.html
  CONTENT_LENGTH_DOWNLOAD_T(CURLINFO.CURLINFO_CONTENT_LENGTH_DOWNLOAD_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CONTENT_LENGTH_UPLOAD.html
  CONTENT_LENGTH_UPLOAD(CURLINFO.CURLINFO_CONTENT_LENGTH_UPLOAD),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CONTENT_LENGTH_UPLOAD_T.html
  CONTENT_LENGTH_UPLOAD_T(CURLINFO.CURLINFO_CONTENT_LENGTH_UPLOAD_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_STARTTRANSFER_TIME.html
  STARTTRANSFER_TIME(CURLINFO.CURLINFO_STARTTRANSFER_TIME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CONTENT_TYPE.html
  CONTENT_TYPE(CURLINFO.CURLINFO_CONTENT_TYPE),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_REDIRECT_TIME.html
  REDIRECT_TIME(CURLINFO.CURLINFO_REDIRECT_TIME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_REDIRECT_COUNT.html
  REDIRECT_COUNT(CURLINFO.CURLINFO_REDIRECT_COUNT),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PRIVATE.html
  PRIVATE(CURLINFO.CURLINFO_PRIVATE),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_HTTP_CONNECTCODE.html
  HTTP_CONNECTCODE(CURLINFO.CURLINFO_HTTP_CONNECTCODE),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_HTTPAUTH_AVAIL.html
  HTTPAUTH_AVAIL(CURLINFO.CURLINFO_HTTPAUTH_AVAIL),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PROXYAUTH_AVAIL.html
  PROXYAUTH_AVAIL(CURLINFO.CURLINFO_PROXYAUTH_AVAIL),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_OS_ERRNO.html
  OS_ERRNO(CURLINFO.CURLINFO_OS_ERRNO),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_NUM_CONNECTS.html
  NUM_CONNECTS(CURLINFO.CURLINFO_NUM_CONNECTS),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SSL_ENGINES.html
  SSL_ENGINES(CURLINFO.CURLINFO_SSL_ENGINES),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_COOKIELIST.html
  COOKIELIST(CURLINFO.CURLINFO_COOKIELIST),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_LASTSOCKET.html
  LASTSOCKET(CURLINFO.CURLINFO_LASTSOCKET),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_FTP_ENTRY_PATH.html
  FTP_ENTRY_PATH(CURLINFO.CURLINFO_FTP_ENTRY_PATH),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_REDIRECT_URL.html
  REDIRECT_URL(CURLINFO.CURLINFO_REDIRECT_URL),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PRIMARY_IP.html
  PRIMARY_IP(CURLINFO.CURLINFO_PRIMARY_IP),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_APPCONNECT_TIME.html
  APPCONNECT_TIME(CURLINFO.CURLINFO_APPCONNECT_TIME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CERTINFO.html
  CERTINFO(CURLINFO.CURLINFO_CERTINFO),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CONDITION_UNMET.html
  CONDITION_UNMET(CURLINFO.CURLINFO_CONDITION_UNMET),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_RTSP_SESSION_ID.html
  RTSP_SESSION_ID(CURLINFO.CURLINFO_RTSP_SESSION_ID),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_RTSP_CLIENT_CSEQ.html
  RTSP_CLIENT_CSEQ(CURLINFO.CURLINFO_RTSP_CLIENT_CSEQ),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_RTSP_SERVER_CSEQ.html
  RTSP_SERVER_CSEQ(CURLINFO.CURLINFO_RTSP_SERVER_CSEQ),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_RTSP_CSEQ_RECV.html
  RTSP_CSEQ_RECV(CURLINFO.CURLINFO_RTSP_CSEQ_RECV),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PRIMARY_PORT.html
  PRIMARY_PORT(CURLINFO.CURLINFO_PRIMARY_PORT),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_LOCAL_IP.html
  LOCAL_IP(CURLINFO.CURLINFO_LOCAL_IP),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_LOCAL_PORT.html
  LOCAL_PORT(CURLINFO.CURLINFO_LOCAL_PORT),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_TLS_SESSION.html
  TLS_SESSION(CURLINFO.CURLINFO_TLS_SESSION),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_ACTIVESOCKET.html
  ACTIVESOCKET(CURLINFO.CURLINFO_ACTIVESOCKET),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_TLS_SSL_PTR.html
  TLS_SSL_PTR(CURLINFO.CURLINFO_TLS_SSL_PTR),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_HTTP_VERSION.html
  HTTP_VERSION(CURLINFO.CURLINFO_HTTP_VERSION),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PROXY_SSL_VERIFYRESULT.html
  PROXY_SSL_VERIFYRESULT(CURLINFO.CURLINFO_PROXY_SSL_VERIFYRESULT),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PROTOCOL.html
  PROTOCOL(CURLINFO.CURLINFO_PROTOCOL),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_SCHEME.html
  SCHEME(CURLINFO.CURLINFO_SCHEME),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_TOTAL_TIME_T.html
  TOTAL_TIME_T(CURLINFO.CURLINFO_TOTAL_TIME_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_NAMELOOKUP_TIME_T.html
  NAMELOOKUP_TIME_T(CURLINFO.CURLINFO_NAMELOOKUP_TIME_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CONNECT_TIME_T.html
  CONNECT_TIME_T(CURLINFO.CURLINFO_CONNECT_TIME_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PRETRANSFER_TIME_T.html
  PRETRANSFER_TIME_T(CURLINFO.CURLINFO_PRETRANSFER_TIME_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_STARTTRANSFER_TIME_T.html
  STARTTRANSFER_TIME_T(CURLINFO.CURLINFO_STARTTRANSFER_TIME_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_REDIRECT_TIME_T.html
  REDIRECT_TIME_T(CURLINFO.CURLINFO_REDIRECT_TIME_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_APPCONNECT_TIME_T.html
  APPCONNECT_TIME_T(CURLINFO.CURLINFO_APPCONNECT_TIME_T),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_RETRY_AFTER.html
  RETRY_AFTER(CURLINFO.CURLINFO_RETRY_AFTER),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_EFFECTIVE_METHOD.html
  EFFECTIVE_METHOD(CURLINFO.CURLINFO_EFFECTIVE_METHOD),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_PROXY_ERROR.html
  PROXY_ERROR(CURLINFO.CURLINFO_PROXY_ERROR),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_REFERER.html
  REFERER(CURLINFO.CURLINFO_REFERER),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CAINFO.html
  CAINFO(CURLINFO.CURLINFO_CAINFO),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_CAPATH.html
  CAPATH(CURLINFO.CURLINFO_CAPATH),

  /// API docs: https://curl.se/libcurl/c/CURLINFO_LASTONE.html
  LASTONE(CURLINFO.CURLINFO_LASTONE),
  ;

  const CurlEasyInfo(this.rawValue);

  final int rawValue;
}
